### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by unkownpit** [MarvinXLII/BravelyRandomize#3]
Its been a while since this happened, but I ran into an issue on 3ds hardware, during a bravely second randomized seed, the freelancer ability was randomized into eye of the wolf, which crashed the game whenever you got into a battle with Janne or Nikolai in your party. I have a feeling there was no animation for them, which caused the crash. I dont have the log anymore, unfortunately, nor the seed number, but I can send the CrowdFS, if that helps.

I would assume this happenes for this ability, but I am no expert.

**Comment by MarvinXLII** [comment]
Thanks for playing. This is a known issue and is documented in the README file under known bugs. There's very little I can do about it, so just follow my instructions and only let Janne and Nikolai use basic attacks. They leave your party so early in the game that it shouldn't be a real issue on playthroughs.

**Comment by unkownpit** [comment]
you misunderstand. it is the "specialty" of the freelancer, which activates
wolf stance as soon as the battle starts.
